apiVersion: v1
data:
  kubesphere.yaml: |
    authentication:
      authenticateRateLimiterMaxTries: 10
      authenticateRateLimiterDuration: 10m0s
      loginHistoryRetentionPeriod: 168h
      maximumClockSkew: 10s
      multipleLogin: True
      kubectlImage: swr.cn-north-4.myhuaweicloud.com/ddn-k8s/docker.io/kubesphere/kubectl:v1.22.0
      jwtSecret: "P82JNXigr4Fmb8PrHp09OogwyvT5GwNu"
      oauthOptions:
        clients:
        - name: kubesphere
          secret: kubesphere
          redirectURIs:
          - '*'
    network:
      ippoolType: none
    multicluster:
      clusterRole: host
      enable: true
      agentImage: swr.cn-north-4.myhuaweicloud.com/ddn-k8s/docker.io/kubesphere/tower:v0.2.0
      proxyPublishService: tower.kubesphere-system.svc
    monitoring:
      endpoint: http://prometheus-operated.kubesphere-monitoring-system.svc:9090
      enableGPUMonitoring: false
    gpu:
      kinds:
      - resourceName: nvidia.com/gpu
        resourceType: GPU
        default: True
    notification:
      endpoint: http://notification-manager-svc.kubesphere-monitoring-system.svc:19093


    terminal:
      image: swr.cn-north-4.myhuaweicloud.com/ddn-k8s/docker.io/library/alpine:3.14
      timeout: 600
    gateway:
      watchesPath: /var/helm-charts/watches.yaml
      repository: swr.cn-north-4.myhuaweicloud.com/ddn-k8s/docker.io/kubesphere/nginx-ingress-controller
      tag: v1.1.0
      namespace: kubesphere-controls-system
kind: ConfigMap
metadata:
  name: kubesphere-config
  namespace: kubesphere-system
